#!/bin/sh
#
# repo https://github.com/nellinux/sysadmin
# wget https://raw.githubusercontent.com/nellinux/sysadmin/master/giovabackup
#

#
#  Costanti
#

VERSION='Tue Apr 7 2014 - rev. 1'

CMDLINE="$0 $@"

APP_NAME=`basename $0 .sh | sed 's/.*\///'`

LOG_DIR="$HOME/giovabackup.log"
LOG_FILE_BASE='giovabackup'

CONTAINER_2='/Volumes/2TBWDSILVER/STORAGE2TBSILVER'
CONTAINER_1='/Users/giovanni/STORAGEMAC'

SERVER_NAME='192.168.1.100'   # eth1
SERVER_STORAGE='/var/storage'
SERVER_LOGIN='giovanni'

#
# Variabili di modulo
#

ts=`date +%Y%m%d%H%M%S`
log_file=$LOG_DIR/$LOG_FILE_BASE          #.$(date +%Y%d%m%H%M%S)


#
# Funzioni
#

log(){
    [ "$VERBOSE" == "--verbose" ] && echo $1
    echo "`date +%b\ %d\ %T` $1" >> $log_file
}


print_env(){
  cat <<EOF
Costanti utilizzate nel programma:
  CONTAINER_1 = $CONTAINER_1
  CONTAINER_2 = $CONTAINER_2
  LOG_DIR = $LOG_DIR
  LOG_FILE_BASE = $LOG_FILE_BASE
  SERVER_NAME = $SERVER_NAME
  SERVER_STORAGE = $SERVER_STORAGE
  SERVER_LOGIN= $SERVER_LOGIN
EOF
}

version(){
    echo $VERSION
}


usage(){
cat <<EOF
NOME: $APP_NAME

SINOSSI: $APP_NAME [OPZIONI] COMANDO

DESCRIZIONE:

     Il programma $APP_NAME sincronizza oggetti del Mac con il server
     di backup.

COMANDI:

     mac-to-server   :  eseguito nel Mac, esegue il backup sul server


OPZIONI:
     -n  dry run
     -h  questo help
     -v  modo prolisso
     -V  stampa le informazioni di versione del programma

FILES:

     Log in $LOG_DIR

EOF
  exit 1
}

work_in_progress() {
cat <<EOF
$(basename $0)
Questa funzionalita' non e' disponibile :-)
EOF

}

#### MAIN ###

EXIT_SUCCESS=0
NOOP=0
INVALID_EXECUTION_HOST=1
FUNCTION_TO_BE_DEFINED=2
DISK_NOT_AVAILABLE=3
DIRECTORY_NOT_WRITABLE=4
DIRECTORY_NOT_READABLE=6
DEVICE_NOT_AVAILABLE=5
SERVER_NOT_AVAILABLE=6
SERVER_STORAGE_NOT_AVAILABLE=7
SERVER_RSYNC_NOT_AVAILABLE=8

#
# Gestione dei parametri e delle opzioni
#
while getopts ":nhVv" option; do
  case $option in
      n)  DRY_RUN='--dry-run'
          ;;

      h)  usage
          exit $EXIT_SUCCESS
          ;;

      v)  VERBOSE='--verbose'
          ;;

      V)  version
          print_env
          exit $EXIT_SUCCESS
          ;;
  esac
done

shift $(($OPTIND - 1))



#
# Funzioni che devono stare qui in quanto hanno bisogno di accedere ai
# valori di alcune variabili di modulo e costanti.
#

additional_notice() {
    if [ "$DRY_RUN" != "--dry-run" ]; then
        cat <<EOF
** TBD **
EOF
    fi
}

dir_is_writable() {
    d=$1
    if [ ! -w "$d" ]; then
        echo "$d non esiste o non e' permesso scrivervi."
        exit $DIRECTORY_NOT_WRITABLE
    fi
}

dir_is_readable() {
    d=$1
    if [ ! -x "$d" ]; then
        echo "$d non esiste o non e' permesso accedervi."
    fi
}

are_objects_readable() {
    dir_is_readable $CONTAINER_1
    dir_is_readable $CONTAINER_2
}

is_remote_not_available(){

    if ! ssh $SERVER_LOGIN@$SERVER_NAME which rsync > /dev/null; then
        echo "rsync in $SERVER_NAME non esiste o non e' permesso accedervi."
        exit $SERVER_RSYNC_NOT_AVAILABLE
    fi

    if ! ping -n -c2 $SERVER_NAME > /dev/null; then
        echo "Il server $SERVER_NAME non e' disponibile."
        exit $SERVER_NOT_AVAILABLE
    fi

    if ! ssh $SERVER_LOGIN@$SERVER_NAME test -w $SERVER_STORAGE; then
        echo "$SERVER_STORAGE in $SERVER_NAME non esiste o non e' permesso accedervi."
        exit $SERVER_STORAGE_NOT_AVAILABLE
    fi
}


mac_to_server() {

    log 'Mac to server sync ...'

    is_remote_not_available
    are_objects_readable

    for container in $CONTAINER_1 $CONTAINER_2; do

        log "Syncing $container to server ... "

        if [ -w "$container" ]; then
            dest_dir=$(basename $container)
            if ssh $SERVER_LOGIN@$SERVER_NAME 'test -w' $SERVER_STORAGE/$dest_dir/ ; then
                [ "$VERBOSE" == "--verbose" ] && echo "rsync -a $VERBOSE  --log-file=$log_file --delete $DRY_RUN  $container/  $SERVER_LOGIN@$SERVER_NAME:$SERVER_STORAGE/$dest_dir/"
                rsync -a $VERBOSE  --log-file=$log_file --delete $DRY_RUN  $container/  $SERVER_LOGIN@$SERVER_NAME:$SERVER_STORAGE/$dest_dir/
            else
                log "$container non sincronizzata ($SERVER_STORAGE/$dest_dir/ non accessibile in scrittura o non esistente in $SERVER_NAME)"
            fi
        else
            log "$container non sincronizzata (non accessibile in scrittura o non esistente in locale)"
        fi
    done
}



#
# Init
#
mkdir -p "$LOG_DIR"
log "Start as \"$CMDLINE\" from `pwd`"

#
# Ciclo dei comandi
#
cmd=$1
case $cmd in

    mac-to-server)
        mac_to_server
        ;;

    *)  usage
        exit $EXIT_SUCCESS
        ;;
esac

exit 0
