#!/bin/sh
#
# nellinux, 2013-11-22
#



if [ "$USER" == 'root' ]; then
    SUDO=""
else
    SUDO="/usr/bin/sudo"
fi

$SUDO /sbin/cryptsetup create --verify-passphrase archivi /dev/sda5 && $SUDO /sbin/mount /dev/mapper/archivi /home/archivi/
