#!/bin/sh
#
#  Sync $ALWAYS_AVALAIBLE_MAILDIR with $OFFLINE_ARCHIVE_MAILDIR
#  Tipically used in cron job.
#

ALWAYS_AVALAIBLE_MAILDIR='/home/tnx/.posta-ricevuta/'
OFFLINE_ARCHIVE_MAILDIR='/home/tnx/.mt/ricevuta/'
WARNING_RCPT='tnx'

EXIT_SUCCESS=0
NOOP=0
SOURCE_NOT_AVAILABLE=-1
DEST_NOT_AVAILABLE=-2


APP_NAME=($basename $0)

log() {
    echo "[$APP_NAME `date +%T`] $1"
    logger $1 -t $APP_NAME
}

usage() {
cat <<EOF
  USAGE:
    $(basename $0) [OPTIONS]

  OPTIONS:
    -h  THIS HELP

  Sync $ALWAYS_AVALAIBLE_MAILDIR with $OFFLINE_ARCHIVE_MAILDIR
  Tipically used in cron job.

EOF
}

mail_send() {
    echo $1 | mail -s "$APP_NAME - warning" $WARNING_RCPT
}

work_in_progress() {
cat <<EOF
$(basename $0)
Function not yet implemented :-)
EOF
}

#### MAIN ###

while getopts ":h" option; do
  case $option in
      h)  usage
          exit $EXIT_SUCCESS
          ;;
  esac
done

shift $(($OPTIND - 1))

if [ ! -r  $ALWAYS_AVALAIBLE_MAILDIR ]; then

    msg="[EE]  $ALWAYS_AVALAIBLE_MAILDIR not available (ALWAYS_AVALAIBLE_MAILDIR)"
    log "$msg"
    mail_send "$msg"
    exit $SOURCE_NOT_AVAILABLE

else
    if [ -w $OFFLINE_ARCHIVE_MAILDIR ]; then
        rsync -av $ALWAYS_AVALAIBLE_MAILDIR $OFFLINE_ARCHIVE_MAILDIR
    else
        msg="[WW]  $OFFLINE_ARCHIVE_MAILDIR not available (OFFLINE_ARCHIVE_MAILDIR)"
        log "$msg"
        mail_send "$msg"
        exit $DEST_NOT_AVAILABLE
    fi
fi

exit $EXIT_SUCCESS
